### ISSUE TITLE
Find Vowels from a Word/String

### ISSUE THREAD

**Issue by srinivasboga** [srinivasboga/Boga_R-D#8]
**Summary**:
--------------
We need to implement a functionality to identify and extract vowels from a given word or string. The implementation should be case-insensitive and consider both uppercase and lowercase vowels.
 

**Checklist**:
-------------
- [ ] The function should take a string input.
- [ ] It should return a list or a string containing only the vowels found in the input.
- [ ] If no vowels are found, it should return an empty list or string.
- [ ] The solution should handle both English uppercase (A, E, I, O, U) and lowercase (a, e, i, o, u) vowels.

**Example Input/Output**:
-----------------------------
- **Input**: "Programming", 
- **Output**: "o"
- **Input**: "Hello World", 
- **Output**: "eoo"

**Additional Notes**:
------------------------
- Please ensure to write unit tests to validate the implementation.
- Consider edge cases, such as an empty string or a string with no vowels.

**Comment by ShubhamNakashe** [comment]
Can I try to solve this ??

**Comment by srinivasboga** [comment]
> Can I try to solve this ??

Yep, try it your own way instead of relying on what’s available on the internet.

**Comment by ShubhamNakashe** [comment]
![image](https://github.com/user-attachments/assets/2f8e5084-bb82-491c-8c7f-d7e0684d7c94)
![image](https://github.com/user-attachments/assets/59b4af4f-3c37-4227-9e44-c70c03e8427f)

Is this Fine ??

**Comment by ShubhamNakashe** [comment]
So Shall I send a PR request now ??

**Comment by ShubhamNakashe** [comment]
Also you have created a new issue for vowel checking junit test, so shall I exclude the testing code from commit of this issue as I have written code for test for the first time.
